export const GET_ALL_TEMPLATES = "GET_ALL_TEMPLATES";
export const LOAD_DATA = "LOAD_DATA";

export const TEMPLATE_START = "TEMPLATE_START";
export const TEMPLATE_ERROR = "TEMPLATE_ERROR";

export const FILTER_BY_VALUE = "FILTER_BY_VALUE";
export const SORT_BY_ALPHABET = "SORT_BY_ALPHABET";
export const SORT_BY_DATE = "SORT_BY_DATE";
export const SORT_BY_ECOMMERCE = "SORT_BY_ECOMMERCE";
export const SORT_BY_HEALTH = "SORT_BY_HEALTH";
export const SORT_BY_EDUCATION = "SORT_BY_EDUCATION";

const LOAD_NEW_PAGE = "LOAD_NEW_PAGE";
const LOAD_EXACT_PAGE = "LOAD_EXACT_PAGE";
