export {
  templates,
  templateStart,
  templateError,
  getAllTemplates,
  filterByValue,
  sortByAlphabet,
  sortByEcommerce,
  sortByEducation,
  sortByHealth,
  sortByDate,
  loadData,
  loadNewPage,
  loadExactPage,
} from "./templates";
