// import Head from 'next/head'
// import Image from 'next/image'
import Layout from "../layouts/landing";
import SearchSort from "../components/home/searchSort";
import Templates from "../components/home/templates";

export default function Home() {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <SearchSort />
      <Templates />
    </>
  );
}

Home.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};
